services:
  - type: web
    name: stress-detection-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: "gunicorn --timeout 300 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
